[msg MSG_000_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0][uf 3 1 1 0 0 1 0 0]Ah...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0][uf 3 1 1 0 0 2 0 0]That old lady... She's Mii-chan-san's owner.[n][uf 1 1][e]

[msg MSG_001_0_0 [Smirking Student]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 3 0 0][uf 5 21 0 2]Hey, Granny, I got a date tomorrow.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 4 0 0][uf 5 21 0 2]But, uh, I don't have any money or anything, you know?[n][uf 1 1][e]

[msg MSG_002_0_0 [Mii-chan's Owner]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 5 0 0][uf 5 21 0 3]Oh my, is that so? Oh, you poor thing.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 6 0 0][uf 5 21 0 3]You've always been such a good boy, Kiyoshi... This advance on your allowance will just be between you and me.[n][uf 1 1][e]

[msg MSG_003_0_0 [Kiyoshi]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 7 0 0][uf 5 21 0 2]C'mon, quit it! I told you not to call me Kiyoshi![n][uf 1 1][e]

[msg MSG_004_0_0 [Mii-chan's Owner]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 8 0 0][uf 5 21 0 3]But it's such a beautiful name! I picked it out myself, you know.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 9 0 0][uf 5 21 0 3]It was the name of a fine doctor from my home village...[n][uf 1 1][e]

[msg MSG_005_0_0 [Kiyoshi]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 10 0 0][uf 5 21 0 2]Yeah, I know, I've heard.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 11 0 0][uf 5 21 0 2]C'mon, hook me up already.[n][uf 1 1][e]

[msg MSG_006_0_0 [Mii-chan's Owner]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 12 0 0][uf 5 21 0 3]Oh, yes, yes.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 13 0 0][uf 5 21 0 3]It's not much, try not to spend it all in one place![n][uf 1 1][e]

[msg MSG_007_0_0 [Kiyoshi]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 14 0 0][uf 5 21 0 2]Sweet, thanks. See ya.[n][uf 1 1][e]

[msg MSG_008_0_0 [Mii-chan's Owner]]
[uf 0 5 65278][uf 2 1][uf 3 1 1 0 0 15 0 0][uf 5 21 0 3]Be careful, and visit again soon![n][uf 1 1][e]

[msg MSG_009_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0][uf 3 1 1 0 0 16 0 0]I have something I want to ask that "Kiyoshi-san"...[n][uf 1 1][e]

