[msg MSG_000_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0][uf 3 1 1 0 0 1 0 0]Could you come a little closer?[n][uf 1 1][e]

[msg MSG_000_3_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 1 65535 65535 0 0][uf 3 1 1 0 0 2 0 0]Ah, right there. That should be good.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 1 65535 65535 0 0][uf 3 1 1 0 0 3 0 0]Okay, here goes.[n][uf 1 1][e]

[msg MSG_001_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 1 65535 65535 0 0][uf 3 1 1 0 0 4 0 0]Ch-Cheese...![n][uf 1 1][e]

[sel SEL_002_0_0 top]
[uf 0 5 65278][uf 2 1]Cheese.[e]
[uf 0 5 65278][uf 2 1]......[e]

[msg MSG_003_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 1 65535 65535 0 0][uf 3 1 1 0 0 5 0 0]Oh, good! It came out nicely this time.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0][uf 3 1 1 0 0 6 0 0][uf 4 23 0 7 0 25 25]I wasn't here when everyone took pictures last time...[n][uf 1 1][e]

[msg MSG_004_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0][uf 3 1 1 0 0 7 0 0]I've wanted to get one with you since.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0][uf 3 1 1 0 0 8 0 0]Technically, I could just capture video data through my eyes...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 3 65535 65535 0 0][uf 3 1 1 0 0 9 0 0][uf 4 23 0 7 3 25 25]But in that situation, I wouldn't be able to appear in the picture myself.[n][uf 1 1][e]

[msg MSG_005_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0][uf 3 1 1 0 0 10 0 0]Oh, I know it's a little late to be asking this, but...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0][uf 3 1 1 0 0 11 0 0]Do you like taking photos, [uf 4 2]-san?[n][uf 1 1][e]

[sel SEL_006_0_0 top]
[uf 0 5 65278][uf 2 1]Yeah, it's fun.[e]
[uf 0 5 65278][uf 2 1]Actually, I don't.[e]

[msg MSG_007_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 1 65535 65535 0 0][uf 3 1 1 0 0 12 0 0]Ah, what a relief.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 1 65535 65535 0 0][uf 3 1 1 0 0 13 0 0]In that case, we should get a "silly one" next time.[n][uf 1 1][e]

[msg MSG_008_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 3 65535 65535 0 0][uf 3 1 1 0 0 14 0 0]I-I'm sorry if I made you uncomfortable.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 1 65535 65535 0 0][uf 3 1 1 0 0 15 0 0][uf 4 23 0 7 1 25 25]I'll make sure to treasure this one![n][uf 1 1][e]

[msg MSG_009_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0][uf 3 1 1 0 0 16 0 0]I think photographs are a truly amazing invention.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0][uf 3 1 1 0 0 17 0 0]They allow us to preserve a single moment in the endless flow of time...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0][uf 3 1 1 0 0 18 0 0]This technology was born from a desire to preserve the experiences that are precious to us.[n][uf 1 1][e]

[msg MSG_010_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 3 65535 65535 0 0][uf 3 1 1 0 0 19 0 0]Until recently, I was sad about the fact that I am a machine... That I'm so different from other people.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0][uf 3 1 1 0 0 20 0 0][uf 4 23 0 7 0 25 25]But after telling you my feelings... I realized something.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 1 65535 65535 0 0][uf 3 1 1 0 0 21 0 0][uf 4 23 0 7 1 25 25]There is one thing only a machine with a human heart can do... That only I can do.[n][uf 1 1][e]

[sel SEL_011_0_0 top]
[uf 0 5 65278][uf 2 1]What's that?[e]
[uf 0 5 65278][uf 2 1]I don't understand.[e]

[msg MSG_012_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0][uf 3 1 1 0 0 22 0 0]No matter how clear our photos and records are, they can't preserve our feelings.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0][uf 3 1 1 0 0 23 0 0]Data and memories aren't the same thing.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0][uf 3 1 1 0 0 24 0 0]Emotions can't be captured by a photograph. They can only continue to exist in our memories.[n][uf 1 1][e]

[msg MSG_012_5_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 3 65535 65535 0 0][uf 3 1 1 0 0 25 0 0]But, we'll all have to say goodbye eventually. And someday, our memories will fade.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0][uf 3 1 1 0 0 26 0 0][uf 4 23 0 7 0 25 25]But, I'm different.[n][uf 1 1][e]

[msg MSG_013_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 1 65535 65535 0 0][uf 3 1 1 0 0 27 0 0]I'm going to keep my memories of everyone alive.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 1 65535 65535 0 0][uf 3 1 1 0 0 28 0 0]Your experiences and feelings will continue to live on, inside of me.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 1 65535 65535 0 0][uf 3 1 1 0 0 29 0 0]I will never forget. Even if you all change, or if time ends up pulling us apart...[n][uf 1 1][e]

[msg MSG_014_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0][uf 3 1 1 0 0 30 0 0]O-Oh, yes... Umm...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0][uf 3 1 1 0 0 31 0 0]Will you take this?[n][uf 1 1][e]

[msg MSG_015_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0][uf 3 1 1 0 0 32 0 0]That's one of my parts that had to be replaced after I collapsed at the Moonlight Bridge.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0][uf 3 1 1 0 0 33 0 0]I asked Mitsuru-san to have it sent here.[n][uf 1 1][e]

[msg MSG_015_3_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 3 65535 65535 0 0][uf 3 1 1 0 0 34 0 0]I kept it hidden until recently, because it reminded me that I'm just a machine...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0][uf 3 1 1 0 0 35 0 0][uf 4 23 0 7 0 25 25]But, not anymore.[n][uf 1 1][e]

[msg MSG_015_7_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0][uf 3 1 1 0 0 36 0 0]Now, it's a symbol to show that I'll always remember you.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0][uf 3 1 1 0 0 37 0 0]This is the proof of my resolve... and I want you to have it.[n][uf 1 1][e]

[msg MSG_016_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0][uf 3 1 1 0 0 38 0 0]I want you to know that as long as I'm here, I will never leave you.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0][uf 3 1 1 0 0 39 0 0]No matter how or when your life comes to an end...[n][uf 1 1][e]

[msg MSG_016_3_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 1 65535 65535 0 0][uf 3 1 1 0 0 40 0 0]At that moment, I will be by your side.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 1 65535 65535 0 0][uf 3 1 1 0 0 41 0 0]Everything that makes you who you are... will live on in my memories.[n][uf 1 1][e]

[msg MSG_016_7_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 1 65535 65535 0 0][uf 3 1 1 0 0 42 0 0]I am your friend, but I am also the machine that will keep your memory alive.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 1 65535 65535 0 0][uf 3 1 1 0 0 43 0 0]Because this is something only I can do.[n][uf 1 1][e]

[msg MND_017_0_0]
[uf 0 5 65278][uf 2 1]Aigis has a genuine smile upon her face.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]I feel a strong bond with Aigis...[n][uf 1 1][e]

[msg SYS_018_0_0]
[uf 0 5 65278][uf 2 1]The Aeon Social Link reached its maximum level! You can now fuse [uf 0 1 35]Metatron[uf 0 1 27], the attendant to the infinite![n][uf 1 1][e]

[msg MSG_019_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 1 65535 65535 0 0][uf 3 1 1 0 0 44 0 0]Oh! Hey, you two! We're hooome![n][uf 1 1][e]

[msg MSG_020_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 1 65535 65535 0 0][uf 3 1 1 0 0 45 0 0]Oh, welcome back... Were you hanging out together?[n][uf 1 1][e]

[msg MSG_021_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 1 65535 65535 0 0][uf 3 1 1 0 0 46 0 0]We ran into each other at the station and, well, I would've felt bad just leaving Junpei behind there.[n][uf 1 1][e]

[msg MSG_022_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 6 65535 65535 0 0][uf 3 1 1 0 0 47 0 0]Uh-huh. You're just so thoughtful, aren'tcha?[n][uf 1 1][e]

[msg MSG_023_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 1 65535 65535 0 0][uf 3 1 1 0 0 48 0 0]Hehe. So, what were you and Aigis up to?[n][uf 1 1][e]

[sel SEL_024_0_0 top]
[uf 0 5 65278][uf 2 1]Taking a picture.[e]
[uf 0 5 65278][uf 2 1]Just chatting.[e]

[msg MSG_025_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 0 65535 65535 0 0][uf 3 1 1 0 0 49 0 0]A picture? Why?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 3 1 65535 65535 0 0][uf 3 1 1 0 0 50 0 0][uf 4 23 0 3 1 25 25]Oh, yeeeah! Ai-chan wasn't there last time![n][uf 1 1][e]

[msg MSG_026_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 1 65535 65535 0 0][uf 3 1 1 0 0 51 0 0]I've actually been wondering for a while now, but what do you two usually talk about?[n][uf 1 1][e]

[msg MSG_027_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 1 65535 65535 0 0][uf 3 1 1 0 0 52 0 0]Today, we were having a very fulfilling discussion about photographs.[n][uf 1 1][e]

[msg MSG_028_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 1 65535 65535 0 0][uf 3 1 1 0 0 53 0 0]Oh, that's right! Why don't we all take a photo together, since we're here?[n][uf 1 1][e]

[msg MSG_029_0_0 [Junpei Iori]]
[uf 0 5 65278][uf 2 1][uf 4 5 3 1 65535 65535 0 0][uf 3 1 1 0 0 54 0 0]Oooh, check it out, we got all the second-years here! Alright, I'm in, let's do it![n][uf 1 1][e]

[msg MSG_030_0_0 [Yukari Takeba]]
[uf 0 5 65278][uf 2 1][uf 4 5 2 0 65535 65535 0 0][uf 3 1 1 0 0 55 0 0]Sure, but who's gonna take it? I don't think we can fit all five of us...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 2 1 65535 65535 0 0][uf 3 1 1 0 0 56 0 0][uf 4 23 0 2 1 25 25]Well, I guess we could just take turns![n][uf 1 1][e]

[msg MSG_031_0_0 [Fuuka Yamagishi]]
[uf 0 5 65278][uf 2 1][uf 4 5 6 1 65535 65535 0 0][uf 3 1 1 0 0 57 0 0]Ah okay, I'll take the first shot. Where does everyone want to stand?[n][uf 1 1][e]

[msg MND_032_0_0]
[uf 0 5 65278][uf 2 1]I spent a long time with everyone...[n][uf 1 1][e]

