[msg MSG_000_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0][uf 3 1 1 0 0 1 0 0]I find myself coming here a lot lately.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 3 65535 65535 0 0][uf 3 1 1 0 0 2 0 0]Before, I couldn't understand the benefits of coming to these "shrines."[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0][uf 3 1 1 0 0 3 0 0]But lately, that's changed...[n][uf 1 1][e]

[msg MSG_001_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0][uf 3 1 1 0 0 4 0 0]This is also where we met Koromaru-san last summer...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0][uf 3 1 1 0 0 5 0 0]He waited here until we found him, even though he knew his master had died.[n][uf 1 1][e]

[msg MSG_002_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0][uf 3 1 1 0 0 6 0 0]I can understand why now.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 3 65535 65535 0 0][uf 3 1 1 0 0 7 0 0]What drives people isn't necessarily facts, but feelings...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 3 65535 65535 0 0][uf 3 1 1 0 0 8 0 0]He knew for a fact that his master had died, but his feelings of wanting to be with him made him stay.[n][uf 1 1][e]

[msg MSG_003_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0][uf 3 1 1 0 0 9 0 0]I feel the same.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0][uf 3 1 1 0 0 10 0 0]I recognized the fact that I can't protect you, but I came back anyway.[n][uf 1 1][e]

[msg MSG_003_3_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0][uf 3 1 1 0 0 11 0 0]Subconsciously, I was acting based on my emotions, rather than logic.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0][uf 3 1 1 0 0 12 0 0]I was so confused at the time that I didn't notice it, but it's true.[n][uf 1 1][e]

[msg MSG_003_5_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 1 65535 65535 0 0][uf 3 1 1 0 0 13 0 0]The parameters governing my behavior seem to have been updated during my time with you, [uf 4 2]-san.[n][uf 1 1][e]

[msg MND_004_0_0]
[uf 0 5 65278][uf 2 1]I can sense Aigis's faint affection...[n][uf 1 1][e]

[msg MSG_005_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0][uf 3 1 1 0 0 14 0 0]...Oh, I misspoke.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0][uf 3 1 1 0 0 15 0 0]I mentioned "what drives people"...[n][uf 1 1][e]

[msg MSG_005_3_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 1 65535 65535 0 0][uf 3 1 1 0 0 16 0 0]But of course, Koromaru-san and myself aren't "people."[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 1 65535 65535 0 0][uf 3 1 1 0 0 17 0 0]Heheh, sorry...[n][uf 1 1][e]

[msg MSG_005_5_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 3 65535 65535 0 0][uf 3 1 0 0 0 18 0 0]......[n][uf 1 1][e]

[msg MND_006_0_0]
[uf 0 5 65278][uf 2 1]Aigis looks somewhat lonely.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]We decided to go back to the dorm.[n][uf 1 1][e]

