[msg MSG_000_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 3 65535 65535 0 0][uf 3 1 1 0 0 1 0 0]There's no trace of her.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 3 65535 65535 0 0][uf 3 1 1 0 0 2 0 0]I can detect hostile readings like Shadows, but when it comes to this...[n][uf 1 1][e]

[msg MSG_000_3_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0][uf 3 1 1 0 0 3 0 0]I'm useless... aren't I?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0][uf 3 1 1 0 0 4 0 0]And I was the one who insisted we search... I'm sorry.[n][uf 1 1][e]

[sel SEL_001_0_0 top]
[uf 0 5 65278][uf 2 1]Don't let it get to you. +0[e]
[uf 0 5 65278][uf 2 1]We should head back for today. +0[e]
[uf 0 5 65278][uf 2 1]Let's keep looking. +0[e]

[msg MSG_002_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 3 65535 65535 0 0][uf 3 1 1 0 0 5 0 0]It's not working out, after all... How could a machine like myself have feelings like a normal person?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 3 65535 65535 0 0][uf 3 1 0 0 0 6 0 0]......[n][uf 1 1][e]

[msg MSG_002_3_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0][uf 3 1 1 0 0 7 0 0]It's getting dark. We should probably give up the search for today.[n][uf 1 1][e]

[msg MSG_002_5_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 1 65535 65535 0 0][uf 3 1 1 0 0 8 0 0]Thank you very much, [uf 4 2]-san.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 1 65535 65535 0 0][uf 3 1 1 0 0 9 0 0]I'm happy that you took the time to indulge me in this.[n][uf 1 1][e]

[msg MSG_003_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0][uf 3 1 1 0 0 10 0 0]Yes, you're right. It's getting dark.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 3 65535 65535 0 0][uf 3 1 0 0 0 11 0 0]......[n][uf 1 1][e]

[msg MSG_003_3_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 3 65535 65535 0 0][uf 3 1 1 0 0 12 0 0]It's not working out, after all... How could a machine like myself have feelings like a normal person?[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0][uf 3 1 1 0 0 13 0 0]Thank you very much, [uf 4 2]-san.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 1 65535 65535 0 0][uf 3 1 1 0 0 14 0 0]I'm happy that you took the time to indulge me in this.[n][uf 1 1][e]

[msg MSG_004_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 1 65535 65535 0 0][uf 3 1 1 0 0 15 0 0]Thank you, [uf 4 2]-san.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 0 65535 65535 0 0][uf 3 1 1 0 0 16 0 0]But it's getting dark. We should probably give up the search for today.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 1 65535 65535 0 0][uf 3 1 1 0 0 17 0 0]I'm happy that you took the time to indulge me in this.[n][uf 1 1][e]

[msg MSG_004_3_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 3 65535 65535 0 0][uf 3 1 0 0 0 18 0 0]......[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 3 65535 65535 0 0][uf 3 1 1 0 0 19 0 0]It's not working out, after all... How could a machine like myself have feelings like a normal person?[n][uf 1 1][e]

[msg MND_005_0_0]
[uf 0 5 65278][uf 2 1]Aigis is smiling...[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1]I feel like I understand[n]Aigis a little better now...[n][uf 1 1][e]

[msg MSG_006_0_0 [Aigis]]
[uf 0 5 65278][uf 2 1][uf 4 5 7 3 65535 65535 0 0][uf 3 1 1 0 0 20 0 0]I'll be going back alone today... I need some time to think.[n][uf 1 1][e]
[uf 0 5 65278][uf 2 1][uf 4 5 7 3 65535 65535 0 0][uf 3 1 1 0 0 21 0 0]I'm sorry... And after you invited me out, too...[n][uf 1 1][e]

[msg MND_007_0_0]
[uf 0 5 65278][uf 2 1]We decided to go back[n]to the dorm separately.[n][uf 1 1][e]

